version: '3.6'
services:
    mssql:
        container_name: "mars_rover_db"
        image: mcr.microsoft.com/mssql/server:latest
        ports:
            - "1433:1433"
        environment:
            ACCEPT_EULA: "true"
            SA_PASSWORD: "mars@1996"